export const demoDatasets: Record<string, { day: string; percentage: number }[]> = {
  "Jul, 2024": [
    { day: "Mon", percentage: 10 },
    { day: "Tue", percentage: 40 },
    { day: "Wed", percentage: 30 },
    { day: "Thu", percentage: 70 },
    { day: "Fri", percentage: 90 },
    { day: "Sat", percentage: 60 },
    { day: "Sun", percentage: 80 },
  ],
  "Aug, 2024": [
    { day: "Mon", percentage: 20 },
    { day: "Tue", percentage: 30 },
    { day: "Wed", percentage: 50 },
    { day: "Thu", percentage: 80 },
    { day: "Fri", percentage: 70 },
    { day: "Sat", percentage: 90 },
    { day: "Sun", percentage: 40 },
  ],
  "Sep, 2024": [
    { day: "Mon", percentage: 50 },
    { day: "Tue", percentage: 60 },
    { day: "Wed", percentage: 70 },
    { day: "Thu", percentage: 80 },
    { day: "Fri", percentage: 90 },
    { day: "Sat", percentage: 40 },
    { day: "Sun", percentage: 30 },
  ],
  "Oct, 2024": [
    { day: "Mon", percentage: 70 },
    { day: "Tue", percentage: 80 },
    { day: "Wed", percentage: 60 },
    { day: "Thu", percentage: 50 },
    { day: "Fri", percentage: 30 },
    { day: "Sat", percentage: 20 },
    { day: "Sun", percentage: 10 },
  ],
  "Nov, 2024": [
    { day: "Mon", percentage: 30 },
    { day: "Tue", percentage: 50 },
    { day: "Wed", percentage: 80 },
    { day: "Thu", percentage: 90 },
    { day: "Fri", percentage: 40 },
    { day: "Sat", percentage: 60 },
    { day: "Sun", percentage: 70 },
  ],
};